name: Release on merge or manual dispatch

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to create (e.g., v1.40.0)'
        required: true

jobs:
  tag-and-release:
    # Run on automated push from Dependabot OR on manual dispatch
    if: (github.event_name == 'push' && github.actor == 'dependabot[bot]' && contains(github.event.head_commit.message, 'modernc.org/sqlite')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create and push tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to check for existing tags

      - name: Determine Version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(grep 'modernc.org/sqlite' go.mod | awk '{print $2}')
          fi
          echo "Using version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and Push Git Tag
        run: |
          TAG_NAME="${{ steps.get_version.outputs.version }}"
          echo "Proposed tag: $TAG_NAME"
          # Check if tag already exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping."
          else
            echo "Creating tag $TAG_NAME"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi
