name: Update README Version

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit and push changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag
        id: get_tag
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Update README.md with new version
        run: |
          NEW_VERSION="${{ steps.get_tag.outputs.TAG }}"
          # Use sed to replace the placeholder with the actual version
          # It now matches 'Current version: vX.Y.Z' and replaces vX.Y.Z with the new version
          sed -i "s/Current version: v[0-9.]*/Current version: $NEW_VERSION/g" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update README.md version to ${{ steps.get_tag.outputs.TAG }}"
          git push
